// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "#F5FCFF",
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      welcome: {
        fontSize: 20,
        textAlign: "center",
        margin: 10
      },
      instructions: {
        color: "#333333",
        textAlign: "center",
        marginBottom: 5
      }
    });

function reducer(state, action) {
  if (action) {
    return state - 1 | 0;
  } else {
    return state + 1 | 0;
  }
}

function App$LocalCounter(Props) {
  var match = React.useReducer(reducer, 0);
  var dispatch = match[1];
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Incr */0);
                    }),
                  title: "+"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Decr */1);
                    }),
                  title: "-"
                }), React.createElement(ReactNative.Text, {
                  children: " counter:" + String(match[0])
                }));
}

var LocalCounter = /* module */[
  /* initialState */0,
  /* reducer */reducer,
  /* make */App$LocalCounter
];

function App$app(Props) {
  var os = ReactNative.Platform.OS;
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: styles.welcome,
                  children: "Welcome to (Reason) React Native!"
                }), React.createElement(ReactNative.Text, {
                  style: styles.instructions,
                  children: "To get started, edit src/App.re"
                }), React.createElement(ReactNative.Text, {
                  style: styles.instructions,
                  children: os === "ios" ? "Press Cmd+R to reload,\nCmd+D or shake for dev menu" : (
                      os === "android" ? "Double tap R on your keyboard to reload,\nShake or press menu button for dev menu" : (
                          os === "web" ? "Press Cmd+R to reload." : ""
                        )
                    )
                }), React.createElement(App$LocalCounter, { }));
}

var app = App$app;

exports.styles = styles;
exports.LocalCounter = LocalCounter;
exports.app = app;
/* styles Not a pure module */
